### ISSUE TITLE
Sovereign Chess: Castling doesn't work

### ISSUE THREAD

**Issue by acornmonkey** [GlukKazan/GlukKazan.github.io#10]
I think you broke castling when adding defection.

**Comment by GlukKazan** [comment]
Can you show an example?

**Comment by acornmonkey** [comment]
<https://www.youtube.com/watch?v=xC6SZwdHiS8>

**Comment by GlukKazan** [comment]
fix: https://github.com/GlukKazan/GlukKazan.github.io/commit/3214a5377c47c481c46d943444310216c117aa84

**Comment by acornmonkey** [comment]
![image](https://user-images.githubusercontent.com/111863988/188519695-09615d17-48d9-4fa1-a3fb-9670d21312c0.png)
Castling still doesn't work for defected kings.

**Comment by GlukKazan** [comment]
Yes I see.

**Comment by GlukKazan** [comment]
Fix: https://github.com/GlukKazan/GlukKazan.github.io/commit/e6c8c2f81ddd680c5f3b3d3a7ba4de3b0e6707e7
