### ISSUE TITLE
Sovereign Chess: White shouldn't be able to move on the second move

### ISSUE THREAD

**Issue by acornmonkey** [GlukKazan/GlukKazan.github.io#11]
For some reason, this repository's Sovereign Chess allows either White or Black to move on the second move. I think you have misunderstood the pie rule. It's not that either White or Black can move on the the second move. It's that the second player gets to either play Black or switch places, so that the first player plays Black.

<https://www.infinitepigames.com/sc-rules>
See Starting the Game.

If the second player chooses to be White, they don't make a move right away. Black gets a turn first. No matter what colour the second player chooses, no colour gets a turn twice in a row. If they switch places, the first player gets two turns in a row, first as White, and then as Black.

**Comment by GlukKazan** [comment]
I no longer remember the implementation details, I'll look at it tomorrow.

**Comment by GlukKazan** [comment]
Temporarily disabled the pie rule: https://github.com/GlukKazan/GlukKazan.github.io/commit/3214a5377c47c481c46d943444310216c117aa84
