### ISSUE TITLE
Stalemate leads to "black lose" result in checkmate/chess-ending-04.htm

### ISSUE THREAD

**Issue by SagePtr** [GlukKazan/GlukKazan.github.io#3]
Here is a screenshot.
![image](https://user-images.githubusercontent.com/3179266/54121177-6e243200-4402-11e9-9361-8645beb1c023.png)
This is stalemate, but game reports "black lose"

**Comment by GlukKazan** [comment]
Yes, I know about it. Current version  does not distinguish stalemate and checkmate.
I will try to fix it

**Comment by GlukKazan** [comment]
https://github.com/GlukKazan/GlukKazan.github.io/commit/d3912b2c477f2f0fed48bf3d27c49007d7a842be
