### ISSUE TITLE
Sovereign Chess: It shouldn't be possible for both squares of a colour to be occupied at the same time

### ISSUE THREAD

**Issue by acornmonkey** [GlukKazan/GlukKazan.github.io#5]
<https://www.infinitepigames.com/sc-rules>
 Rule 13 is "Only one square of each color may be occupied at a time". But [this repository's Sovereign Chess](https://glukkazan.github.io/checkmate/sovereign-chess-board.htm) allows both squares of a colour to be occupied at the same time.

**Comment by GlukKazan** [comment]
This is a very difficult game. The bug is reproduced, I'll see how it can be fixed.

**Comment by GlukKazan** [comment]
Fixed: https://github.com/GlukKazan/GlukKazan.github.io/commit/d447f1d90c84dabd95a796cf5f9405e21fd73e07
Let me know if something is broken

**Comment by acornmonkey** [comment]
![image](https://user-images.githubusercontent.com/111863988/188519392-f895e9f2-f6b4-4366-9d8d-7e33f353e292.png)
This issue has re-emerged. I shouldn't have been able to put the white knight on h6 when the black pawn was already on i11.
