### ISSUE TITLE
Sovereign Chess: Certain illegal pawn captures are allowed

### ISSUE THREAD

**Issue by acornmonkey** [GlukKazan/GlukKazan.github.io#6]
<https://www.infinitepigames.com/sc-rules>
Rule 6 is "Pawns move orthogonally (horizontally or  vertically) and capture diagonally, as long as the movement is closer to at least one of the brown lines (designating the center of the board)".

In [this repository's Sovereign Chess](https://glukkazan.github.io/checkmate/sovereign-chess-board.htm), this rule is slightly more permissive. Captures are allowed as long as they do not move away from both brown lines at the same time. This means that captures that move away from one brown line and cross the other, such as m9 to n8, are allowed. Such captures shouldn't be allowed because they do not approach any brown line.

Note that non-capturing pawn moves that cross a brown line, such as j11 to i11, are not allowed, either in this implementation or in the official rules.

**Comment by GlukKazan** [comment]
Fixed: https://github.com/GlukKazan/GlukKazan.github.io/commit/77b6d1b6ba9bf0ff7363b1f9d6c50c8bd8adffac
