### ISSUE TITLE
Anti King Chess: You shouldn't be able to put your king in check by putting it in front of a Berolina pawn

### ISSUE THREAD

**Issue by acornmonkey** [GlukKazan/GlukKazan.github.io#8]
When playing [Anti King Chess](https://glukkazan.github.io/checkmate/anti-king.htm), I found that I can put my king in check by putting it in front of a Berolina pawn. When I do this, the AI's Berolina pawn captures my king, but the game goes on.

**Comment by GlukKazan** [comment]
Fixed: https://github.com/GlukKazan/GlukKazan.github.io/commit/6db5ed5bc670f9bcfdf26ff3e842d96a93b5534a
