### ISSUE TITLE
Anti King Chess: Kings shouldn't attack anti-kings

### ISSUE THREAD

**Issue by acornmonkey** [GlukKazan/GlukKazan.github.io#9]
<https://www.chessvariants.com/diffobjective.dir/anti-king-chess.html>
This error really ruins the game, if you ask me. The anti-king can easily just stick to the opponent's king to avoid losing. A king can never move more than one square, except on its first move.

**Comment by GlukKazan** [comment]
I don't quite understand what I can do about this?

**Comment by acornmonkey** [comment]
Add the rule that kings can't attack anti-kings. So you cannot stick to the opponent's king to avoid losing.

**Comment by GlukKazan** [comment]
Is this covered by the original rules?

**Comment by acornmonkey** [comment]
On <https://www.chessvariants.com/diffobjective.dir/anti-king-chess.html>
> This page is written by the game's inventor, [Peter Aronson](https://www.chessvariants.com/who/PeterAronson).
> Kings do not attack Anti-Kings, so an Anti-King next to a hostile King but not attacked by any other piece is not attacked and so in check.

**Comment by GlukKazan** [comment]
Ok, done: https://github.com/GlukKazan/GlukKazan.github.io/commit/02cfa6086d9d22d544889ec19740cc3be47ee8e9
